- jenkins_job:
    config: "{{ lookup('template', 'templates/github.xml.j2') }}"
    name: test
    url: "http://{{jenkins_hostname}}:{{jenkins_http_port}}"
    user: "{{jenkins_admin_username}}"
    password: "{{jenkins_admin_password}}"