---
- name: Create folders
  file: path="{{item}}" state=directory group="{{nginx_user}}" owner="{{nginx_user}}"
  with_items:
    - "/var/www/{{ server_name }}/current"
    - "/var/www/{{ server_name }}/logs"