# 
# ansible-galaxy install geerlingguy.php
# https://galaxy.ansible.com/geerlingguy/php/
# 
---
- hosts: all
  vars:
    php_webserver_daemon: nginx
    php_enable_php_fpm: true
    php_fpm_listen: "127.0.0.1:9000"
    php_fpm_listen_allowed_clients: "127.0.0.1"
    php_fpm_pm_max_children: 50
    php_fpm_pm_start_servers: 5
    php_fpm_pm_min_spare_servers: 5
    php_fpm_pm_max_spare_servers: 5
    php_enable_apc: false
    php_opcache_enable: 0
    php_packages:
      - php72w
      - php72w-cli
      - php72w-common
      - php72w-fpm
      - php72w-pdo
      - php72w-mysql
      - php72w-xml
      - php72w-mbstring
      - php72w-intl
      - php72w-bcmath

  roles:
    - { role: cleanphp.php }
    - { role: geerlingguy.php }

  tasks:
    - name: Install composer
      shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - shell: php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - shell: php composer-setup.php
    - shell: php -r "unlink('composer-setup.php');"

    - name: Move composer to /usr/local/bin
      shell: mv composer.phar /usr/local/bin/composer

    - name: Install git
      yum: name=git state=present
