# 
# ansible-galaxy install geerlingguy.mysql
# https://galaxy.ansible.com/geerlingguy/mysql
# 
---
- hosts: database
  vars:
    mysql_user_name: root
    mysql_user_password: cleanphp-secret
    mysql_root_password_update: yes
    mysql_databases:
      - name: example_db
        encoding: utf8
        collation: utf8_general_ci
    mysql_users:
      - name: cleanphp_user
        host: "%"
        password: cleanphp-double-secret
        priv: "example_db.*:ALL"
  roles:
    - { role: geerlingguy.mysql }
      become: yes
